version: 2

project_name: gocube_ble_library

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gocube
    main: ./cmd/gocube
    binary: gocube
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: gocube
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: SeamusWaldron
    name: gocube_ble_library
  draft: false
  prerelease: auto
  name_template: 'v{{.Version}}'
